data_collection_paths:
  data_sources_json: "artifacts/data/data_sources/agri_data_sources.json"
  collected_data_dir: "artifacts/data/collected_data"
  arxiv_dir: "artifacts/data/collected_data/arxiv"
  core_json_files:
    - "artifacts/data/data_sources/core_data_1748674199.json"
    - "artifacts/data/data_sources/core_data_1748675418.json"

LOG_PATH: "logs"
SOURCE_DATA_PATH: "artifacts/data/collected_data/"
SOURCE_DIRS: ["arxiv", "pdfs", "core"]
DATA_PATH: "artifacts/data/grouped_data/"
GROUPED_DIRS: ["group_1", "group_2", "group_3", "group_4", "group_5", "group_6", "group_7", "group_8", "group_9", "group_10", "group_11", "group_12", "group_13"]


# 🔄 TF-IDF specific database paths
TFIDF_DB_PATH: "artifacts/vectorstores/tfidf_index.pkl"
TFIDF_META_PATH: "artifacts/vectorstores/tfidf_metadata.json"

QUERY_TEXT: "What is the main advantage of YieldNet over traditional single-crop yield prediction models using remote sensing data?"
EVALUATION_DATA_PATHS: "artifacts/data/evaluation_data/questions_1.json"
RESULTS_CSV_PATH: "artifacts/results/evaluation_results.csv"

CHUNK_SIZE: 512
CHUNK_OVERLAP: 50
CHUNK_LOWER_LIMIT: 100
CHUNK_UPPER_LIMIT: 500
BATCH_SIZE: 64
K: 10
R: 5
N: 3

ENCODING_MODEL: "cl100k_base"
EMBEDDING_MODEL: "BAAI/bge-small-en"
RE_RANK_MODEL: "cross-encoder/ms-marco-MiniLM-L-6-v2"
LOCAL_LLM: "qwen3:0.6b"