data_collection_paths:
  data_sources_json: "artifacts/data/data_sources/agri_data_sources.json"
  collected_data_dir: "artifacts/data/collected_data"
  arxiv_dir: "artifacts/data/collected_data/arxiv"
  core_json_files:
    - "artifacts/data/data_sources/core_data_1748674199.json"
    - "artifacts/data/data_sources/core_data_1748675418.json"

LOG_PATH: "logs"
DATA_PATH: "artifacts/data/collected_data/"
CHROMA_DB_PATH: "chromadb"

EVALUATION_DATA_PATHS: "data/evaluation_data/questions.json"
RESULTS_CSV_PATH: "artifacts/results/evaluation_results.csv"

CHUNK_SIZE: 500
CHUNK_OVERLAP: 50
BATCH_SIZE: 64
K: 5
N: 3

# EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_MODEL: "BAAI/bge-small-en"
LOCAL_LLM: "llama3.2"