LOG_PATH: "logs"
GAME_RULES_DATA_PATH: "data/"
CHROMA_DB_PATH: "chromadb"

EVALUATION_DATA_PATHS: 
  - "data/evaluation_data/questions_01.json"
  - "data/evaluation_data/questions_02.json"
RESULTS_CSV_PATH: "artifacts/results/evaluation_results.csv"

CHUNK_SIZE: 800
CHUNK_OVERLAP: 80
BATCH_SIZE: 64
K: 5

# EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_MODEL: "BAAI/bge-small-en"
GENERATION_MODEL: "llama3.2"